### ISSUE TITLE
Hello, how can i get the embedding data?

### ISSUE THREAD

**Issue by xhran2010** [dmpierre/LINE#2]
after i trained a model, how can i get the embedding data of the nodes?

**Comment by dmpierre** [comment]
Hello :)

You should be able to retrieve them using the `model.pt` output file.
Upon instantiation, the model will have a `nodes_embeddings` attribute containing the embedding data (`contextnodes_embeddings` is also available if you trained with second order).

**Comment by xhran2010** [comment]
I got it! thanks! but now i have another issue. i already put the tensors and the model to GPU, but my CPU is still occupied fully. could you please help me find out why?

**Comment by xhran2010** [comment]
is it because the sample progress will cost abundant CPU resources?

**Comment by dmpierre** [comment]
The alias-sampling speed is indeed cpu-bound :)
